services:
  - type: web
    name: mcnab-store-inventory
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: DATA_DIR
        value: /app/data
    disk:
      name: inventory-data
      mountPath: /app/data
      sizeGB: 1
